### PR TITLE
Replaced line 40 of ApplicationController.java with my own informatio…

### PR DESCRIPTION
**Pull request by kirkpatt**
…n.

### CODE REVIEW

**Comment by MichaelHilton** [comment]
So I wanted you to actually add your line in addition to mine, so that once everyone is done, we will have an array with everyone who has run it successfully.  So the correct code is leave my line, then add your code on the line directly after it.  If you make that change and then commit it to your github repo, it will automatically become part of this pull request and then I will accept it.

**Comment by kirkpatt** [comment]
I attempted that, and it seemed to make one of the tests fail. I'll give it
another shot though.

**Comment by MichaelHilton** [comment]
Well, the test is failing because it is expecting the wrong answer.  I am glad you actually ran the tests :+1:   go ahead and change the test to make it pass.

**Comment by kirkpatt** [comment]
These tests are greek to me, so this may take a while. Time to learn java.

**Comment by MichaelHilton** [comment]
Take your time. JUnit does take a little time to wrap your head around. We can just leave this pull request open till you figure it out

**Comment by kirkpatt** [comment]
Success? This made all the tests work, but if this isn't the solution I'm going to stop just taking shots in the dark and actually figure out what I'm looking at.

**Comment by MichaelHilton** [comment]
Great job!!

**Comment by kirkpatt** [comment]
Woo!

**Pull request merged**
