### PR TITLE
Assignment0 complete

### PR DESCRIPTION
**Pull request by Codysseus**
I added a function call to add an object with my info in it.

### CODE REVIEW

**Comment by MichaelHilton** [comment]
Please check the tests. They should all pass. I think you will find that one of them doesn't pass now. I will leave this open, you can make the change, commit it, and it will automatically become part of this pull request. Then I will merge it. Thanks!

**Comment by MichaelHilton** [comment]
Looks Good :+1:

**Comment by Codysseus** [comment]
I fixed the testing function and committed. This should be ready to merge!

**Comment by DesertBeagle** [comment]
I fixed the testing function and committed. This should be ready to merge!

**Comment by DesertBeagle** [comment]
I fixed the testing function and committed. This should be ready to merge!

**Comment by DesertBeagle** [comment]
I fixed the testing function and committed. This should be ready to merge!

**Comment by DesertBeagle** [comment]
I fixed the testing function and committed. This should be ready to merge!

**Comment by DesertBeagle** [comment]
I fixed the testing function and committed. This should be ready to merge!

**Comment by DesertBeagle** [comment]
I fixed the testing function and committed. This should be ready to merge!

**Comment by DesertBeagle** [comment]
I fixed the testing function and committed. This should be ready to merge!

**Comment by DesertBeagle** [comment]
I fixed the testing function and committed. This should be ready to merge!

**Comment by DesertBeagle** [comment]
I fixed the testing function and committed. This should be ready to merge!

**Comment by DesertBeagle** [comment]
I fixed the testing function and committed. This should be ready to merge!

**Comment by DesertBeagle** [comment]
I fixed the testing function and committed. This should be ready to merge!

**Comment by DesertBeagle** [comment]
I fixed the testing function and committed. This should be ready to merge!

**Comment by DesertBeagle** [comment]
I fixed the testing function and committed. This should be ready to merge!

**Comment by DesertBeagle** [comment]
I fixed the testing function and committed. This should be ready to merge!

**Comment by DesertBeagle** [comment]
I fixed the testing function and committed. This should be ready to merge!

**Comment by DesertBeagle** [comment]
I fixed the testing function and committed. This should be ready to merge!

**Comment by DesertBeagle** [comment]
I fixed the testing function and committed. This should be ready to merge!

**Comment by DesertBeagle** [comment]
I fixed the testing function and committed. This should be ready to merge!

**Comment by DesertBeagle** [comment]
I fixed the testing function and committed. This should be ready to merge!

**Comment by DesertBeagle** [comment]
I fixed the testing function and committed. This should be ready to merge!

**Comment by DesertBeagle** [comment]
I fixed the testing function and committed. This should be ready to merge!

**Comment by DesertBeagle** [comment]
I fixed the testing function and committed. This should be ready to merge!

**Comment by DesertBeagle** [comment]
I fixed the testing function and committed. This should be ready to merge!

**Comment by DesertBeagle** [comment]
I fixed the testing function and committed. This should be ready to merge!

**Comment by DesertBeagle** [comment]
I fixed the testing function and committed. This should be ready to merge!

**Comment by DesertBeagle** [comment]
I fixed the testing function and committed. This should be ready to merge!

**Comment by DesertBeagle** [comment]
I fixed the testing function and committed. This should be ready to merge!

**Comment by DesertBeagle** [comment]
I fixed the testing function and committed. This should be ready to merge!

**Comment by DesertBeagle** [comment]
I fixed the testing function and committed. This should be ready to merge!

**Comment by DesertBeagle** [comment]
I fixed the testing function and committed. This should be ready to merge!

**Comment by DesertBeagle** [comment]
I fixed the testing function and committed. This should be ready to merge!

**Comment by DesertBeagle** [comment]
I fixed the testing function and committed. This should be ready to merge!

**Comment by DesertBeagle** [comment]
I fixed the testing function and committed. This should be ready to merge!

**Comment by DesertBeagle** [comment]
I fixed the testing function and committed. This should be ready to merge!

**Comment by DesertBeagle** [comment]
I fixed the testing function and committed. This should be ready to merge!

**Pull request merged**
